services:
  jupyter:
    build: .
    container_name: mission6_jupyter
    ports:
      - "8886:8888"
    volumes:
      - .:/app
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5005
    networks:
      - mission6_net
    depends_on:
      - mlflow

  mlflow:
    build: .
    container_name: mission6_mlflow
    command: mlflow server --host 0.0.0.0 --port 5005 --backend-store-uri /app/mlruns --default-artifact-root /app/mlruns --allowed-hosts '*'
    ports:
      - "5006:5005"
    volumes:
      - ./mlruns:/app/mlruns
    networks:
      - mission6_net

networks:
  mission6_net:
    driver: bridge
